### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by LittleBigMC** [ImagicalDevs/UltimateSurvivalGames#3]
LOL

**Comment by TheKnightGamer** [comment]
It look so but imagicalgamer has random armour and we don't want that

**Comment by Taki21** [comment]
Its not a copy

**Comment by Taki21** [comment]
If u can look i Edited, and put it "in my own coding words"

**Comment by TheKnightGamer** [comment]
Yeah I see that .

**Comment by Taki21** [comment]
Also, I used a way DIFFERENT Strategt .... check

**Comment by TheKnightGamer** [comment]
I see OK I am done I give up on plugin developing

**Comment by Taki21** [comment]
are u leaving??? :{

**Comment by TheKnightGamer** [comment]
Yes or maybe

**Comment by Taki21** [comment]
...

**Comment by Taki21** [comment]
COME ON YOU ARE GOOD AT DEVELOPING DONT GIVE UP! GET UP AND CONTINUE!

**Comment by TheKnightGamer** [comment]
I am to lazy and anything I do is just never goes right like this organization.

**Comment by Taki21** [comment]
I dont do things right either, we all make mistakes

**Comment by TheKnightGamer** [comment]
I make the most out of all.

**Comment by TheKnightGamer** [comment]
I think I will just make a website of how to make a plugin and done.

**Comment by Taki21** [comment]
Well That doesnt matter we are ALL Different

**Comment by TheKnightGamer** [comment]
I will stick with plugin development but I have school so I can still help.

**Comment by LittleBigMC** [comment]
@TheKnightGamer if u fall, we fall with you!

**Comment by LittleBigMC** [comment]
U didnt make the mistakes, we did

**Comment by TheKnightGamer** [comment]
Lol is lol

**Comment by LittleBigMC** [comment]
Lol what?? XD that made no sense

**Comment by Taki21** [comment]
`Call To A Member Function Lol() on Null on Line 3,276,382,383,219,001
`

**Comment by LittleBigMC** [comment]
Lol

**Comment by Taki21** [comment]
`Call To A Member Function Lol() on Null on Line 3,276,382,383,219,001 in LittleBigMC/LoL/Lol.php
`

**Comment by Taki21** [comment]
`Call To A Member Function closeGithubIssue() on Null on Line 3,276,382,383,219,001
`

**Comment by Taki21** [comment]
`Call To A Member Function reopenGithubIssue() on Null on Line 3,276,382,383,219,001
`

**Comment by TheKnightGamer** [comment]
what

**Comment by Taki21** [comment]
`Call To A Member Function what() on Null on Line 3,276,382,383,219,001
`

**Comment by LittleBigMC** [comment]
LOOIL THIS IS FUNNY

**Comment by TheKnightGamer** [comment]
When is the SG going to be finish

**Comment by Taki21** [comment]
It is Now Im adding OTHER features

**Comment by TheKnightGamer** [comment]
Kit must be editable in config.

**Comment by TheKnightGamer** [comment]
Effect what that

**Comment by ImagicalGamer** [comment]
I said he can use whatever from my plug so not stealing/copying xD.

**Comment by TheKnightGamer** [comment]
Yeah it not stealing or copying he had permission.

**Comment by Taki21** [comment]
Yup U see? xD I didnt exactly copy xD

**Comment by Taki21** [comment]
Oh btw i tested it @ImagicalGamer but something is wrong with sign?

**Comment by Taki21** [comment]
(for dis plugin) when i tap sign it doesnt tp to arena? any suggestions?

**Comment by LittleBigMC** [comment]
Public function onInteract(PlayerInteractEvent $e){
// add if the player taps a sign with the words [SGU] or something at thr
top ot teleports him

**Comment by TheKnightGamer** [comment]
Yes that will work because it let's a player touch a sign.

**Comment by LittleBigMC** [comment]
Guys i added that in but can u plz edit cause idk what u want the sign to say or how to make the player join the game. Thanks

**Comment by LittleBigMC** [comment]
Line 104 i think

**Comment by LittleBigMC** [comment]
@Taki21

**Comment by TheKnightGamer** [comment]
@ImagicalGamer Can you help me with kits but no random kits.

**Comment by ImagicalGamer** [comment]
Yea.

**Comment by ImagicalGamer** [comment]
You want custom kits right?

**Comment by TheKnightGamer** [comment]
Yeah

**Comment by Taki21** [comment]
lol

**Comment by TheKnightGamer** [comment]
@Taki21 it over dude its over

**Comment by Taki21** [comment]
i know...

**Comment by TheKnightGamer** [comment]
We can still continue it I have very good plans for this plugin just put it on your profile.

**Comment by Taki21** [comment]
ok but soon i gtg

**Comment by TheKnightGamer** [comment]
First give me Owner.

**Comment by MCUnderground** [comment]
Wtf is this? :)

**Comment by Taki21** [comment]
xD

**Comment by TheKnightGamer** [comment]
Hey who knows Java and JavaScript

**Comment by MCUnderground** [comment]
Why ask?

**Comment by TheKnightGamer** [comment]
I am working on a new project its a app that let's you run any server software with easy setup, plugins and all softwares.

**Comment by MCUnderground** [comment]
I know java, and i dont see where it needs js... Also it is pretty much bad idea, php7 is not recommended on android.

**Comment by TheKnightGamer** [comment]
There is a way to put php7 on android don't you see modified apk of Pocketmine in php7.

**Comment by MCUnderground** [comment]
I didn't say you can't, it is just unstable. Android is best using php 5...
